### ISSUE TITLE
Users presence 

### ISSUE THREAD

**Issue by Amoodaa** [Amoodaa/digiroom#6]
business requirement:
- [x] Users want to be able to see who joined the room
- [x] Users want to see who left the room
- [x] Users want to have a username (simple, no account creation needed)
- [x] Users want to be able to chat with that user name on their messages

### Checklist:
- [x] First user in a room is the creator of the room
- [x] when users join the room, add them in the users list + send a message in chat model + state is online
- [x] Front: add input field for user name on room creation
- [x] Add popup to joining an existing room
